### ISSUE TITLE
Crash without Refined Storage installed

### ISSUE THREAD

**Issue by mcadventurecity** [SirStendec/WirelessUtilities#1]
Hello,

I am developing a modpack, and am experiencing a crash, which only occurred after I installed your mod. It mentions Refined Storage in the crash report, which I do not have installed, making me think that it may have something to do with your integration with that mod. Attached is a crash report.
[crash-2018-11-20_15.40.31-client.txt](https://github.com/SirStendec/WirelessUtilities/files/2601727/crash-2018-11-20_15.40.31-client.txt)

**Comment by Lordmau5** [comment]
I've just setup a Jenkins for our mod, took a bit longer but a build is now up:
https://jenkins.lord.moe/job/Wireless%20Utilities/12/

Would be cool if you could give it a go and see if it still crashes (it didn't during my testing before, but it doesn't hurt 😄 )
