### ISSUE TITLE
A config option to disable machines upgrades crafting

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#11]
I mean by disabling this option will require machines to be upgraded only by applying upgrades in world

Maybe even an other way around option. Begin able to upgrade machines only via crafting and no longer using upgrades

**Comment by SirStendec** [comment]
Basic implementation in 50f39f08dba44a05844b2eeb03eec8a2717e06db

In the long run, we need to start registering those recipes dynamically.
