### ISSUE TITLE
Crafttweaker error when trying to set various level fields (NegativeArraySizeException)

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#12]
crafttweaker.log: https://hastebin.com/isepotagil.md
script: https://hastebin.com/osuzuhidav.cs
log: https://hastebin.com/hayijujexe.md

Reported to Crafttweaker too, don't know which mod is causing this: https://github.com/CraftTweaker/CraftTweaker/issues/783

**Comment by Insane96** [comment]
Crafttweaker might have gone crazy yesterday (and me after it) but now everything works properly (after casting some numbers to long)

**Comment by Insane96** [comment]
Oh sheet
Log: https://hastebin.com/awalomicaf.md
Script: https://hastebin.com/osuzuhidav.cs

**Comment by Insane96** [comment]
Tried with only Crafttweaker, Thermal and Wireles utilities installed. Changed the logs in the first post

**Comment by Insane96** [comment]
Seems like an error on Crafttweaker's end

**Comment by SirStendec** [comment]
I've looked into it a bit, and I have to assume it's on CraftTweaker's end too. The only difference in our code between the properties that work and the properties that are causing errors is that the working ones are long and the erroring ones are int.

I'll be following the CT issue.
