### ISSUE TITLE
Player Positional Cards can't be configured?

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#20]
I don't know if the description is misleading but "[...] and to open a GUI to for setting what can be accessed", but shift-rightclicking does nothing

Edit I would chenge "for setting" to "to set", I'm not english native but sounds better.

Edit 2: Oh, I see ... https://github.com/SirStendec/WirelessUtilities/blob/master/src/main/java/com/lordmau5/wirelessutils/item/ItemPlayerPositionalCard.java#L126 I would then change the title of the issue to "Player Positional Cards tooltip is shift-right-clickbait"

**Comment by SirStendec** [comment]
Woops. I totally forgot to fix the tooltip for that. Thanks for pointing it out.
