### ISSUE TITLE
[Suggestion] A way to tell the Block Augment to not destroy certain blocks

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#23]
I've tried using the crop and block augment to make a tree farm. The problem is that the crop augment can only plant and can only harvest crops and not tree. So I've tried to use the Block augment (inverted) but that would destroy sapings too. So I've come up with something like this but the bottom block is a problem.
![2019-05-13_19 37 01](https://user-images.githubusercontent.com/7185104/57642004-a852b100-75b6-11e9-834f-9bef08b3deb1.png)
I would suggest a way to filter blocks that the Block augment can break or make the crop augment work on trees.

**EDIT**: or **even better** make a separate augment for trees (well, "**Tree Augment**")

**Comment by SirStendec** [comment]
Crop Augments should be able to process trees. Just tested it in my dev environment and it's still working fine for me. Make sure you haven't set process trees to off in the augment config, I suppose?

I do agree that a filter for Block Augments would be good, though. I'd also like to set up a blacklist system for desublimators to let pack devs stop them from picking up certain things.

**Comment by SirStendec** [comment]
I think I might know your issue. Crop Augments will only harvest trees starting at the bottom block. If you start one block up, it won't grab the trees.

**Comment by Insane96** [comment]
Uhm, I had Tree's config disabled ... ops. The Crop Augment tooltip should mention trees too. For the filter what about a "Filter Augment" that can be right-clicked to be configured?

**Comment by SirStendec** [comment]
A Filter Augment could be a good idea.

For now, I've added a blacklist in config to let pack devs stop the desublimator from working on certain blocks. Also added a tooltip to Crop Augments that mentions trees when trees aren't disabled in config.
