### ISSUE TITLE
[Huge suggestion] A way to transport players

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#25]
This might be out of scope of the mod, but I mean there are crop augments so why no "teleporting" or "player" augments?

**Comment by SirStendec** [comment]
I personally feel that this is outside the scope of the mod at this time. I'm not sure how precisely we'd go about fitting entity teleportation into our existing machines. Maybe something to do with enhanced pearls. Stabilized Ender Pearls already do something kind of interesting by teleporting nearby entities to themselves when they hit a surface.

**Comment by SirStendec** [comment]
Vaporizers can now teleport entities, as well as push them around.
