### ISSUE TITLE
Directional Desublimator with crop augment stopped working with trees

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#26]
I have this setup:
![2019-05-13_21 24 54](https://user-images.githubusercontent.com/7185104/57648408-b78d2b00-75c5-11e9-8cc3-a5219d62cbc9.png)

The left desublimator plants saplings, 
![2019-05-13_21 25 09](https://user-images.githubusercontent.com/7185104/57648410-b78d2b00-75c5-11e9-9b1b-7341e036ae1c.png)

the right one harvests trees.
![2019-05-13_21 25 12](https://user-images.githubusercontent.com/7185104/57648411-b78d2b00-75c5-11e9-9d65-0ab598287097.png)

The right stopped working after a while
![2019-05-13_21 18 00](https://user-images.githubusercontent.com/7185104/57648504-f3c08b80-75c5-11e9-839c-0c37fc24c9d7.png)
So I destroyed everything and placed it again ... nothing, the tree did grow but nothing is happening.

That's the right desublimator debug infos with the Debug Bed
https://hastebin.com/ijerodazud.md

**Comment by SirStendec** [comment]
I rewrote a lot of tree handling today, so hopefully things just work better now. Logs shouldn't get stuck anymore, and leaves only occasionally. Better performance too.

**Comment by Insane96** [comment]
It now works properly (even the stuck Desublimator started working) and yep, rarely leaves are left but not a big deal.
