### ISSUE TITLE
Desublimator is missing one block on tilling

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#28]
![2019-05-14_09 08 25](https://user-images.githubusercontent.com/7185104/57677881-31ee9700-7628-11e9-99d2-eb2c353ba4ed.png)

**Comment by Lordmau5** [comment]
So far I wasn't able to reproduce this in-dev... I had a 9x9x9 area built up with a "water pillar" in the center so the Farmland would remain.

It did take a while until all of the Grass was turned into Farmland, but it ended up being tilled.
![image](https://user-images.githubusercontent.com/1345036/57717218-fe892800-767a-11e9-829e-1eaf00f6de54.png)

I did talk about this with Stendec yesterday though and he suggested that we should just... not till Grass and Dirt. It should be up to the player to supply the Farmland.

**Comment by Insane96** [comment]
It's pretty strange issue. Btw I agree to make the player supply Farmland, but the hoe in the recipe would not really make sense.

For the issue I will try to check the block.

**Comment by SirStendec** [comment]
As for auto-tilling, I want to make that configurable so pack devs can choose if they want it or not.

**Comment by Lordmau5** [comment]
Alright, got fixed in the newer build (at least I really hope so).
Plus, there's a configuration option now in regards to auto-tilling.

Additionally, if you want a more direct way of communication, you can add me on Discord and I can add you to a small group chat :P
Lordmau5#0001
