### ISSUE TITLE
[Suggestion] positional wireless redstone

### ISSUE THREAD

**Issue by g-rock84** [SirStendec/WirelessUtilities#34]
Think of the possibilities? I just figured it would be a pretty neat idea. Especially for redstone lights and maybe mob farms.

**Comment by SirStendec** [comment]
It's definitely something we've considered, but there isn't a good way to implement remote redstone at this time. We'd need to have a core mod for modifying how World looks up redstone levels.

That said, I'd be totally interested in supporting it if there was a coremod for that with an API, but I'm not aware of any and I'm also not sure where I'd start with something like that myself.

For now, this isn't feasible and I'm going to close the issue.
