### ISSUE TITLE
Old is New

### ISSUE THREAD

**Issue by ifficles** [SirStendec/WirelessUtilities#4]
Hello There,

  Please have a look at the following pictures.

![2019-02-08_20 59 57](https://user-images.githubusercontent.com/961490/52515729-0ef5b680-2be5-11e9-98bd-7c9734b72535.png)

  After upgrading to the latest version of Wireless Utilities (1.3.29), when the world loads, RS is working for just a few moments, and then goes offline.

![2019-02-08_21 00 50](https://user-images.githubusercontent.com/961490/52515730-0ef5b680-2be5-11e9-8153-69d62975140a.png)

  In order to get Refined Storage working again, I have to break & place the controller.

  As far as I know, this is an old bug that was supposedly quashed by the Refined storage mod creator.

![2019-02-08_21 00 56](https://user-images.githubusercontent.com/961490/52515731-0ef5b680-2be5-11e9-9aad-cf3bd417e569.png)

  Now, I placed a positional Rs network thingy aka "node."

![2019-02-08_21 01 04](https://user-images.githubusercontent.com/961490/52515732-0ef5b680-2be5-11e9-9594-0a9451547e95.png)

  This is what happened after breaking the "node."  Refined storage is offline once again.  So, I end up having to break & replace the controller once again to get Rs back online.

  For the time being, I am going to downgrade to the 1.2.22 version of wireless utilities to resolve this bug.

Modlist:
  ActuallyAdditions-1.12.2-r144
  ActuallyBaubles-1.12-1.1
  ae2stuff-0.7.0.4-mc1.12.2
  AkashicTome-1.2-12
  angelRingToBauble-1.12-0.3.1.50+d4e654e
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-6
  Aroma1997Core-1.12.2-2.0.0.0.b162
  Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37
  AromaBackup-1.12.2-3.0.0.0.b116
  AttributeFix-1.12.2-1.0.4
  AutoRegLib-1.3-24
  Avaritia-1.12.2-3.3.0.28-universal
  badwithernocookiereloaded-1.12.2-3.3.16
  base-1.12.2-3.10.0
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  BetterBuildersWands-1.12.2-0.12.1.254+27f21b9
  BetterFps-1.4.8
  BetterQuesting-3.5.280
  BetterQuestingTriggerer-1.0
  bonsaitrees-1.1.2-b144
  Bookshelf-1.12.2-2.3.569
  Botania+r1.10-358
  BrandonsCore-1.12.2-2.4.9.195-universal
  BringMeTheRings-0.4
  buildcraft-7.99.18
  BuildingGadgets-2.5.0
  Ceramics-1.12-1.3.6
  Chameleon-1.12-4.1.3
  ChanceCubes-1.12.2-3.2.3.242
  ChestTransporter-1.12.2-2.8.8
  chickens-6.1.0
  ClientTweaks_1.12.2-3.1.11
  Clumps-3.1.1
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CoFHCore-1.12.2-4.6.1.22-universal
  CoFHWorld-1.12.2-1.3.0.6-universal
  ColossalChests-1.12.2-1.6.11
  comforts-1.12.2-1.3.1
  CommonCapabilities-1.12-1.4.0
  compacter-1.3.0.3-mc1.12.2
  compactmachines3-1.12.2-3.0.13-b236
  CompactSolars-1.12.2-5.0.18.341-universal
  ComputerCraft1.80pr1
  Controlling-3.0.6
  CookingForBlockheads_1.12.2-6.4.69
  CraftingTweaks_1.12.2-8.1.9
  CraftTweaker2-1.12-4.1.12
  Cucumber-1.12.2-1.1.3
  CustomMainMenu-MC1.12.2-2.0.8
  cxlibrary-1.12.1-1.6.1
  Cyclic-1.12.2-1.17.14
  CyclopsCore-1.12.2-0.11.11
  DankNull-1.12-1.4.46
  DarkUtils-1.12.2-1.8.222
  DefaultOptions_1.12.2-9.2.8
  Draconic-Evolution-1.12.2-2.3.18.329-universal
  ducky-mod-1.12.2-0.1.0
  EnchantingTable-1.12-1.1.3
  EnderCore-1.12.2-0.5.43
  EnderIO-1.12.2-5.0.39
  EnderIO-endergy-1.12.2-5.0.39
  EndermanEvolution-1.12.2-1.0.15
  EnderStorage-1.12.2-2.4.5.135-universal
  environmentaltech-1.12.2-2.0.19.1
  EquivalentAdditions-1.12.2-3r
  etlunar-1.12.2-2.0.19.1
  EvilCraft-1.12.2-0.10.64
  Exchangers-1.12.2-2.8
  ExCompressum_1.12.2-3.0.26
  exnihilocreatio-1.12-0.3.2
  ExtraCells-1.12.2-2.6.1a
  extrautils2-1.12-1.9.8
  ExtremeReactors-1.12.2-0.4.5.50
  FarmingForBlockheads_1.12.2-3.1.26
  FastLeafDecay-v14
  FeaturedServers-1.12-1.0.6
  fluxnetworks-1.12.2-3.0.19-21
  foamfix-0.10.3-1.12.2
  forestry_1.12.2-5.8.2.380
  Forgelin-1.8.2
  ForgeMultipart-1.12.2-2.6.0.79-universal
  ForgivingVoid_1.12.2-1.0.21
  FTBLib-5.4.0.73
  FTBUtilities-5.3.0.68
  FullscreenWindowed-1.12-1.6.0
  GooglyEyes-1.12.2-7.0.2
  Guide-API-1.12-2.1.8-63
  HammerCore-1.12.2-2.0.4.1
  Harvest-1.12-1.2.7-20
  hatchery-1.12.2-2.1.4
  Hwyla-1.8.26-B41_1.12.2
  iChunUtil-1.12.2-7.1.4
  ieclochecompat-2.0.6
  ImmersiveEngineering-0.12-88
  industrialcraft-2-2.8.108-ex112
  industrialforegoing-1.12.2-1.12.4-228
  industrialmeat-1.12-1.0.2
  InGameInfoXML-1.12.2-2.8.2.94-universal
  IntegratedDynamics-1.12.2-0.11.18
  IntegratedTunnels-1.12.2-1.5.6
  IntegrationForegoing-1.12.2-1.8.2
  InventoryTweaks-1.64+dev.143
  ironchest-1.12.2-7.0.54.838
  itemscroller-1.12.2-0.12.0
  JEHC-1.12.2-1.6.2.0
  jei_1.12.2-4.14.4.252
  jeibees-0.9.0.5-mc1.12.2
  jeivillagers-1.12-1.0.2
  journeymap-1.12.2-5.5.3
  JustEnoughIDs-1.0.2-26
  KleeSlabs_1.12.2-5.4.11
  llibrary-1.7.17-1.12.2
  longfallboots-1.2.1b
  LootBags-1.12.2-2.5.7
  LootingModMC1.12.2-1.1
  LunatriusCore-1.12.2-1.2.0.42-universal
  Mantle-1.12-1.3.3.39
  mcjtylib-1.12-3.0.7
  MCMultiPart-2.5.3
  Mekanism-1.12.2-9.4.13.349
  MekanismGenerators-1.12.2-9.4.13.349
  MekanismTools-1.12.2-9.4.13.349
  Mercurius-1.12.2
  missing_pieces-1.12.2-4.3.0
  MobGrindingUtils-0.3.13
  modnametooltip_1.12.2-1.10.0
  Modpack Configuration Checker-1.12.2-v1.6
  modtweaker-4.0.15
  MooFluids-1.12.2-1.8.12.02a
  moreavaritia-mc1.12.2-2.4
  morechickens-1.12.2-3.1.0
  MoreFurnaces-1.12.2-1.10.6
  moreoverlays-1.14-mc1.12.2
  Morpheus-1.12-3.3.2
  Morph-o-Tool-1.2-21
  MouseTweaks-2.9-mc1.12.2
  MPUtils-1.12.2-1.5.6
  MTLib-3.0.5
  MultiPageChest-1.12-1.9.1
  MysticalAgradditions-1.12.2-1.2.10
  MysticalAgriculture-1.12.2-1.7.1
  natura-1.12.2-4.3.2.66
  Neat 1.4-17
  NetherPortalFix_1.12.1-5.3.17
  nice-1.12-0.3.1
  NoMoreRecipeConflict-0.12(1.12.2)
  NoNVFlash-1.12.2-1.2.0.3-universal
  noRecipeBook_v1.2.2formc1.12.2
  notenoughwands-1.12-1.7.1
  OldJavaWarning-1.12.2-1.0.6
  OpenBlocks-1.12.2-1.8
  OpenModsLib-1.12.2-0.12.1
  oreberries-1.12.x-0.5.0
  OreExcavation-1.4.133
  OreSpawn-1.12-3.3.0.155
  p455w0rdslib-1.12.2-2.0.36
  Pam's HarvestCraft 1.12.2za
  Pam's Simple Recipes 1.12.2c
  pamsimpleharvest-2.0.0
  Placebo-1.12.2-1.5.0
  plustic-7.0.0.0
  ProjectE-1.12-PE1.3.2h
  Psi-r1.1-69
  QuantumStorage-1.12-4.6.5
  RandomThings-MC1.12.2-4.2.5
  randomtweaks-1.12.2-2.4.0.7
  rangedpumps-0.5.1-12
  RealisticItemDrops-1.2.14
  reauth-3.6.0
  RebornCore-1.12.2-3.13.1.402-universal
  RebornStorage-1.12.2-3.3.2.79
  RedstoneArsenal-1.12.2-2.6.1.15-universal
  RedstoneFlux-1.12-2.1.0.6-universal
  refined_avaritia-1.12.2-2.4
  refinedstorage-1.6.13-362
  refinedstorageaddons-0.4.3-25
  Reliquary-1.12.2-1.3.4.780
  ResourceLoader-MC1.12.1-1.5.3
  rflux-1.12-0.3.0
  rftools-1.12-7.59
  rftoolsctrl-1.12-1.9.2
  rftoolsdim-1.12-5.63
  roost-1.12-1.3.0
  Signals-1.12.2-1.3.13-28-universal
  SimpleCorn1.12-1.12-2.4.1
  simplegenerators-1.12.2-2.0.19.1
  SlimyBoyos-1.0.0
  SmoothFont-mc1.12.2-1.16.2
  Snad-1.12.1-1.7.09.16a
  SolarFluxReborn_1.12.2-4.32r
  sonarcore-1.12.2-5.0.19-20
  stacksize-1.12.2-1.0
  StandardExpansion-3.4.145
  StoneBlockUtilities-2.1.1
  StorageDrawers-1.12.2-5.3.8
  TConstruct-1.12.2-2.11.0.106
  Tesla-1.12.2-1.0.63
  tesla-core-lib-1.12.2-1.0.15
  ThermalCultivation-1.12.2-0.3.1.8-universal
  ThermalDynamics-1.12.2-2.5.3.16-universal
  ThermalExpansion-1.12.2-5.5.2.39-universal
  ThermalFoundation-1.12.2-2.6.1.22-universal
  ThermalInnovation-1.12.2-0.3.1.8-universal
  tinker_io-1.12.2-rw2.7.0a
  TinkerToolLeveling-1.12.2-1.1.0
  tinyprogressions-1.12.2-3.3.31-Release
  tmel-1.12.2-1.2.1.0
  Toast Control-1.12.2-1.7.1
  torchmaster_1.12.2-1.6.4.62
  Translocators-1.12.2-2.5.1.77-universal
  TS2K16-1.2.10
  UniDict-1.12.2-2.9.2
  usefulnullifiers-1.5.0
  valkyrielib-1.12.2-2.0.19.1
  voidislandcontrol-1.5.1
  WanionLib-1.12.2-2.2
  Wawla-1.12.2-2.5.264
  weirdinggadget-1.12.2-2.0.5-universal
  Whoosh-1.12.2-0.1.12.1-universal
  WirelessCraftingTerminal-1.12.2-3.10.82
  wirelessutils-1.12.2-1.2.24-universal
  Wither+Skeleton+Tweaks-1.12.2-2.6.2
  woot-1.12.2-1.4.9
  worldprimer-1.12.2-0.5.0
  xnet-1.12-1.7.5
  zerocore-1.12-0.1.2.3

  If you need any other information, please do not hesitate to send me a message.  BTW, thanks for the mod

**Comment by Lordmau5** [comment]
You mentioned that you downgraded to 1.2.22 - is the bug not occuring on that version?

If it isn't, that means something during the changes from 1.2 to 1.3 have messed up how both RS and AE are working and that might make it easier to trace down *why* the issue is occuring in code

**Comment by ifficles** [comment]
Thank you for the quick response.  And, to answer your question, yes the above bug is not occurring the 1.2.22 version of the mod.

  However, you may not need to go to that far back on versions.  I did download, some time ago, from your Jenkins site, a beta version 1.3.25, that was also not affected by the above bug.

**Comment by Lordmau5** [comment]
Right, Jenkins was causing some issues on my server (for whatever reason it managed to create a **200GB log file**) so I changed some settings temporarily and as a side-effect it caused old builds to be deleted sadly...

But I should know where the issue is occuring now, I'll look into it later today :)

**Comment by Lordmau5** [comment]
Alright, the issue should be taken care of, but before we upload it on CurseForge, it would be cool if you could have a look at it as well again and see if it still happens to you :)

https://jenkins.lord.moe/job/Wireless%20Utilities/31/

**Comment by ifficles** [comment]
I'm testing right now.  After logging in, Rs is online and working just fine.  As before, when I place & break the Wireless Rs node, Refined storage stays online.  Many thanks

**Comment by Lordmau5** [comment]
Perfect! Means we can upload it to CurseForge!

Sorry for the issues that were caused by one of the recent updates, but thank you for reporting this so we could actually fix it! :D
