### ISSUE TITLE
Dropped fluxed pearls dropped as item seems like to not exist

### ISSUE THREAD

**Issue by Insane96** [SirStendec/WirelessUtilities#43]
![2019-08-10_12 38 56](https://user-images.githubusercontent.com/7185104/62820918-0c602380-bb6c-11e9-88fc-d276df890581.png)

**Comment by SirStendec** [comment]
Fixed in 6b8586abf408ea18038ca7fa425f5331ca0acdb3

Wireless Utilities pearls can be matched with `@e[type=wirelessutils:item]`
