### ISSUE TITLE
Crash with latest Release

### ISSUE THREAD

**Issue by ifficles** [SirStendec/WirelessUtilities#60]
Hello LordMau & SirStendec,

  So, here's what has happened.  As yous see by the title, I upgraded to the last release of wireless utils 1.8.126.  Here's the first error after the game loads - https://paste.ee/p/69wjJ

  Now, here is where the "fun" happens.  I was re-establishing all network connections with the positional Rs block and absolute positional cards.  I happened upon a block that would not be broken with an owner not being set.  After a few attempts, the block broke on its own.  I discarded that item into the void.

  I then went over to a refined storage network receiver, right-clicked that block with an absolute positional card to lock in the coordinates & nothing happened.  I did this as well, several times.  I'd say 30 seconds later the game froze, and then went to the desktop with the following error message - https://paste.ee/p/BjZHW

  I am playing the modern skyblock classic mod pack.  If either of you wishes, I can make the save file & full log available.

  I will try & upgrade to the latest beta release off of the Jenkins page, to see if that clears up the issues.  Otherwise, I'll downgrade to the 7.76 version release

**Comment by Insane96** [comment]
I can't open the logs you sent

**Comment by SirStendec** [comment]
Thanks for the report. I was able to identify the source of the exception and the commit I just pushed should resolve the problem. I'm in bed right now so I can't fire up the game to check, but this is such an obvious fix I feel bad for missing the problem in the first place.

Should be fixed in the latest dev build:

https://jenkins.lord.moe/job/Wireless%20Utilities/129/

**Comment by ifficles** [comment]
> 
> 
> I can't open the logs you sent

Wow, did I made a mistake?  I've corrected the links to the errors above

**Comment by Insane96** [comment]
It didn't work on phone, but on pc it downloaded the file. Changing /d/ to
/p/ fixed it for me.

Il Gio 19 Set 2019, 01:35 ifficles <notifications@github.com> ha scritto:

**Comment by SirStendec** [comment]
I'm going to go ahead and close this issue now, as I'm pretty certain the new release (v1.9) has this bug fixed. Please don't hesitate to comment if it's not and I'll re-open the issue.
