### ISSUE TITLE
Can't duplicate animated blocks

### ISSUE THREAD

**Issue by Pival81** [SirStendec/WirelessUtilities#61]
I want to duplicate animated blocks from Erebus with the duplicate module on the vaporizer, but when I try to insert the void pearl with the animated block it doesn't let me insert it.

**Comment by SirStendec** [comment]
I'm not at my PC right now so I can't test anything, but here's what I assume is happening.

Vaporizers, with the default configuration, calculate how much fuel is needed to duplicate a mob by attempting to read the experienceValue field of the mob. If a creature doesn't drop exp, or uses a different way of calculating how much exp to drop, the Vaporizer can't calculate a cost for the mob.

If the calculated cost is zero, it won't let you spawn copies of a mob.

You can get around this by changing the Fuel - Experience Factor and Fuel - Health Factor config options for Vaporizers > Modules > Duplication Module / Theoretical Slaughter Module.
