### ISSUE TITLE
[Suggestion] machine or augment to input and output from the same machine

### ISSUE THREAD

**Issue by Chrysheart** [SirStendec/WirelessUtilities#62]
Maybe make a machine or augment that lets you both input and output from the same machine. For example, I am using filing cabinets, storage drawers, and potion shelves and would like the to access everything from my ae 2 terminal. I know there is an i/o augment and that may be exactly it, but I have not had any luck figuring that out

**Comment by SirStendec** [comment]
I'm afraid that doesn't really make sense with how things are implemented.
