### ISSUE TITLE
Crashes when using AE Machines to connect to Dense Cables

### ISSUE THREAD

**Issue by Chrysheart** [SirStendec/WirelessUtilities#66]
First off. Wireless Utilities interaction with dense smart cables is weird. Regular smart cables seem fine though. If you start a world, place down a power cell and  a positional ae network, then you place 5 me drives around one dense smart cable, set the position of an absolute positional card to the dense smart cable, put it in the positional ae network (at this point the smart cable will give a weird message instead of displaying channels). The smart dense cable now seems to be unable to be registered as broken, but we are gonna go a step further. When you take the positional card back out, you can break the dense cable for real and then place the card back in. Now when you place a dense smart cable where it is already registered it will crash your game and any time you try to reload in, it will kick you right out.

I have tested this multiple times and it may be doable with less steps, but I am not sure. I am also not sure whether it is ae2 causing it or wireless utilities. I have ae 2 at the most recent update at the time and same with wireless utilities. Forge is version 14.23.5.2816

-Thank you for looking into this

**Comment by andr9528** [comment]
Connecting a positional ae network (tested with tier 5) to a dense smart cable crashes the game instantly, as mentioned above. Works fine with Dense conduit from Ender IO thought, it seems.

AE2 Version: appliedenergistics2-rv6-stable-7
Wireless Utilities Version: wirelessutils-1.12.2-1.10.136-universal
COFH Core Version: CoFHCore-1.12.2-4.6.3.27-universal
Forge Version: forge-14.23.5.2847
Minecraft 1.12.2

**Comment by andr9528** [comment]
after further inspection it seems that it takes the dense me conduit as a simple smart cable, limiting it to 8 channels

**Comment by SirStendec** [comment]
Hey, sorry it's taken me so long to look into this. I've been very busy with other projects.

From what I've discovered, this is a problem on the AE2 side of things. When it's generating the model for a dense cable, it doesn't check if the connection has a side before trying to get the tile at that offset. Our connection is tagged as "internal" which has a facing of null. It tries to get the block offset at null side, and crashes with a NPE.

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/parts/networking/PartDenseCable.java#L79
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/parts/networking/PartDenseCable.java#L134

I'm going to open an issue with AE2.

**Comment by SirStendec** [comment]
I've written a pull request against Applied Energistics 2 to fix this problem. It's a very simple fix: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/4255

Unfortunately they don't keep their CI in working order so I can't link a build for you to try, but hopefully it's merged soon.

**Comment by SirStendec** [comment]
The Applied Energistics 2 dev has decided not to fix the bug. I find their decision regrettable but whatever, it's their mod and they can do what they want with it.

The next version of Wireless Utilities will, accordingly, just not connect to dense cables specifically. EnderIO conduits will work fine. Non-dense cables will work fine. Machines will work fine.

Just not dense cables because they have a NPE bug in their rendering code that the dev won't fix. I'm doing more work on AE2 for the next version, with less network invalidations, support for color filtering, better GUIs, and an option to make machines not use a channel.

The block against dense cables is already done, so I'm going to close this issue now.
