### ISSUE TITLE
Invalid block State ??? - Related to #42

### ISSUE THREAD

**Issue by ifficles** [SirStendec/WirelessUtilities#67]
I was hoping to be able to upload a picture directly.  However, I'll have to utilize an indirect method.  Please go here:  https://www.4shared.com/s/fw3HP3yimea

  So, here's what has happened.  I placed, in the picture, a desublimator against the side of a void ore miner.  And you can see the result.  To fix the issue, I had to place the desublimator not directly against the miner, but at the diagonal.  There are no crash logs, and I'm playing a pack that I made.

  This is not a big issue, more of a visual bug, that just so happens to have appeared.  As always, thanks for looking into this.

**Comment by ifficles** [comment]
Hello LordMau, Sirstendec, & anyone else.  I forgot to say what version of the pack I'm using, it is the latest release for wireless utilities.  Unfortunately, I have to retract my statement above.  This has turned into a big issue.  Please have a look at the following pictures;

https://imgur.com/a/whaKYqo

  Now, the first block next to the copper chest was a positional charger tier 4, with augments that were all tier 4.  And, a tier 2 target augment, with 5 absolute positional cards.  The next two blocks were positional condensers, tier 4, with tier 4 capacity, and inventory augments.  Those were targeting the chests to the left.

  The last block on the right was a tier 4 positional charger, with a tier 4 capacity card, and inventory augment.  And, that block was targeting a chest behind.

  What has happened, so far, is when I go into a simple void world using the portal block, everything is fine.  But when I return using the same method, the textures of the affected blocks turn into what you saw in the pictures.  The tier 4 upgrades do not stay, and all the augments are deleted.

  I've tried using the crescent hammer in the last photo to rotate the blocks, in hopes of preserving the contents & upgrades.  But, alas, that did not work.  If you wish, I can provide a download link for my pack, for testing purposes.

  Also, the Jenkins site is down again.

**Comment by SirStendec** [comment]
Hello. Sorry for taking so long to get back to you on this. I've been very busy with other projects and just haven't had the time to devote to fun side-projects like Minecraft.

If you still have the pack, could you let me know what's in it? I've had a few reports about invalid block state issues but I've been unable to reproduce them locally. I'm assuming that there's another mod messing with blockstates and incorrectly overwriting the state of one of WU's machines.

**Comment by ifficles** [comment]
Apologies are neither needed nor warranted.  We've all got lives outside of the "net."  I am happy that you've responded to my request.  You are in luck, I do still have it.

![snap1](https://user-images.githubusercontent.com/961490/72578433-af476700-389b-11ea-89c3-4d2d1dd57ed1.png)
![snap2](https://user-images.githubusercontent.com/961490/72578435-afdffd80-389b-11ea-9b19-cfd1edc06c15.png)
![snap3](https://user-images.githubusercontent.com/961490/72578436-afdffd80-389b-11ea-96ca-2ce90d86959f.png)
![snap4](https://user-images.githubusercontent.com/961490/72578437-afdffd80-389b-11ea-9c9b-a6adb19fbe09.png)
![snap5](https://user-images.githubusercontent.com/961490/72578439-afdffd80-389b-11ea-8a5f-1b9a0c2fc34b.png)

  So, this pack is just over 200 mods.  And, I'm sorry about that.  I know having that many, won't help narrow the bug down.  However, I can upload my pack, as it is, to offsite storage for you to download and try?

**Comment by SirStendec** [comment]
Whew, yeah, I should have expected a pack like that. It shouldn't be too bad. Just have to delete mods half at a time till I can't reproduce the problem anymore.

Hopefully it's something reasonably easy to guess like BetterFPS. If you want to upload it, go ahead and I'll check it out this weekend.

**Comment by ifficles** [comment]
Good Afternoon, as requested, here's the link - http://tinyurl.com/senjcrj .  So, the pack is within the 1.12.2.zip file, and the rest of the files, in that folder, are the automated backups.  By the way, I do not remember if I told you, but I do use multimc to play.  thanks

**Comment by SirStendec** [comment]
I've been playing around with your pack a bit, and I'm afraid I just can't reproduce the state errors at all. I tried using a new map, the most recent save included in the pack download, and the 2019-11-30 backup.

**Comment by ifficles** [comment]
No need for fear.  I figured this bug would've eventually righted itself, after updating some mods.  It may come back, then again it might not.  There's no way to tell at this time.  For now, I'm going to close this issue.  If it comes back, I'll file another bug request
