### ISSUE TITLE
Crash and lose access to world #2

### ISSUE THREAD

**Issue by Whitebrim** [SirStendec/WirelessUtilities#69]
Added inventory upgrade to wireless charger that covers the whole my base. Server crashed and cannot start anymore.
I have RS storage, some EnderIO tech and CookingForBlockheads storages. I tested them all in solo and it didn't crash.
Repeating is set to "Circling".

Slightly useless log, but you can find what line it crash:
[crash-2020-01-14_21.57.04-server.txt](https://github.com/SirStendec/WirelessUtilities/files/4061153/crash-2020-01-14_21.57.04-server.txt)

**Comment by tie** [comment]
We were able to add a workaround for the issue on the server. This could be the actual fix, but I have no idea what the hell is going on in `performWork`.

**Comment by tie** [comment]
@Whitebrim waiting for your feedback. I’ll open a PR if everything is fine.

**Comment by Whitebrim** [comment]
@tie It works well now
