### ISSUE TITLE
[Bug] Latest Release eats a absurd amount of ram, literally 2x the entire modpack

### ISSUE THREAD

**Issue by Akitori** [SirStendec/WirelessUtilities#7]
Hi yes, I don't know why but the latest wireless utilities decided to eat all the ram i have avaiable. I was curious as to why, watched it during loading, and found that for some reason it was creating more textures than normal???

What is going on? Why is these eating more ram that literally Tinker's, Rustic, Thaumcraft and Natura **combined?**

**Comment by SirStendec** [comment]
Thanks for bringing this to my attention, I think I know what's causing this. I'll do some testing and try to get a fixed build out tonight if I can manage it.

**Comment by SirStendec** [comment]
Closed in 638f7ef82a38cebcadb4c9f61f3ef515f28c0739
