### ISSUE TITLE
Crash when using Morerefinedstorage(rs fork)

### ISSUE THREAD

**Issue by River277** [SirStendec/WirelessUtilities#74]
When using the MoreRefinedstorage fork of refined storage 1.12.2 it crashes when a rs connecter from wirelessutilities is placed

The morerefinedstorage fork remade the autocrafting system causing it to make large scale crafting alot easier with alot less lag as well.

[crash-2023-04-14_16.59.31-server.txt](https://github.com/SirStendec/WirelessUtilities/files/11237102/crash-2023-04-14_16.59.31-server.txt)

here is the crash log, called it a class error of some sort, so hopefully just a change in location causing it to crash.

P.s. Love the mod its alot of fun to play with

**Comment by Lordmau5** [comment]
Yeah it seems the `OneSixMigrationHelper` class isn't present anymore in that fork...

It seems we are only using that class in one spot though, so and it's a migration helper for an older version of Refined Storage to a newer one from my understanding, so might be able to just remove it...

I am currently having a bit of an issue trying to setup the development environment so I'll take a look at it in the coming days though - honestly, seems like an easy fix on paper 😁

**Comment by Lordmau5** [comment]
Okay I gave it another try to setup a developer environment for 1.12 to try and fix this, but since that game version is so massively outdated I can't easily ask anyone for help.

Most of the dependencies just fail to resolve and thus don't get downloaded, resulting in errors.
Even trying to fetch basic resources from Minecraft's server is resulting in errors.

I'm gonna keep this issue open in case someone else would find some time to fix this :(

At this point I think it's easier to just... port the mod to newer versions entirely.

**Comment by kappa-maintainer** [comment]
WirelessUtilities is using a seriously outdated mdk build script, you can find the latest template [here](https://github.com/CleanroomMC/TemplateDevEnv/)
As for closed maven sites, [CurseMaven](https://www.cursemaven.com/) can always work as an alternative

**Comment by Lordmau5** [comment]
> WirelessUtilities is using a seriously outdated mdk build script, you can find the latest template [here](https://github.com/CleanroomMC/TemplateDevEnv/) As for closed maven sites, [CurseMaven](https://www.cursemaven.com/) can always work as an alternative

Oh sick, I'll give that a go later tonight! Thank you so much for the pointers! ♥️
I didn't even know there was a mdk build script with a newer FG version for 1.12.2

**Comment by Lordmau5** [comment]
Man holy hell, I massively apologize for the delay on this, I just got way too occupied with a lot of other stuff in my life

**BUT**
![image](https://github.com/SirStendec/WirelessUtilities/assets/1345036/90ad1b0d-ea08-4522-8de3-5decee1ca663)

It works again :)

Thanks @kappa-maintainer for the RetroFuturaGradle link once more ♥️

Grab 1.10.137 from here and please report back if you are still having issues:
https://curseforge.com/minecraft/mc-mods/wireless-utilities/files/4713543

**Comment by Lordmau5** [comment]
I'm gonna assume this is fixed - if there are stil issues with this in the future please open up another issue :)

I can't promise that I'll be able to fix a lot of things on 1.12 anymore though as I am slowly working on a 1.20 port with a friend
