### ISSUE TITLE
Crash with Refined Storage on server

### ISSUE THREAD

**Issue by aking4125** [SirStendec/WirelessUtilities#75]
Hello,

Upon adding this mod (Version 1.10.137), the server crashes on startup with the following report: 

[crash-2023-08-21_05.26.26-server.txt](https://github.com/SirStendec/WirelessUtilities/files/12394653/crash-2023-08-21_05.26.26-server.txt)

We're using normal Refined Storage (Version 1.6.16).

This seems to be a different problem from this issue here: https://github.com/SirStendec/WirelessUtilities/issues/74

Single player works fine. Removing this mod allows the server to load normally.

Any ideas?

**Comment by Lordmau5** [comment]
Interesting! Seems I forgot to test the server-side in the dev environment - I am getting crashes with not just Refined Storage but also Applied Energistics

It tries to load a client class (`IItemColor`) on the server-side

Could you try it with this version please?
[wirelessutils-1.10.138.zip](https://github.com/SirStendec/WirelessUtilities/files/12394919/wirelessutils-1.10.138.zip)

**Comment by aking4125** [comment]
Copy that. Will give this a test in a moment.

Thank you for the response!

**Comment by Lordmau5** [comment]
No problem! I'm glad that, at least in testing just now, it was a simple fix 😄

**Comment by aking4125** [comment]
That fixed it yes! Thank you so much!
